baseURL: "https://www.cuck.church/"
languageCode: "en-us"
title: "cuck.church"
theme: "church"
menu:
    main: []
params:
  podcast:
    title: cuck.church
    description: A collection of pseuds, shitposters, and actual scholars who convene every other Sunday to discuss capitalism, art, history, religion, and cyberculture.
    image: podcast.png
    category:
      name: "Society & Culture"
      subcategories: ["Philosophy"]
    explicit: true
    lang: English
    cdn: https://cuckpodcasts.blob.core.windows.net/podcasts
  dateFormat: "Jan 2 2006"
  mobileMenu: false
  showMenu: false
  footer: "All content, code, and assets GPL. [GitHub](https://github.com/djmadeira/cuck-dot-church)"
  feedLinks: true

