name = "church"
description = "A modification of the Zen theme"
homepage = ""
license = "GPLv2"
licenselink = "http://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
tags = ["accessible", "multilingual", "responsive", "blog", "search", "micro", "podcast"]
features = ["accessible", "multilingual", "responsive", "grid", "sass", "search", "matamo", "jsonfeed", "subtheme", "podcast"]
min_version = "0.67.1"

[author]
  name = "DJ Madeira"

[original]
  name = "Fredrik Jonsson"
  homepage = "https://xdeb.net/"
  repo = "https://github.com/frjo/hugo-theme-zen.git"
